CREATE TABLE EATS AS SELECT * FROM CAFE;

SELECT * FROM EATS;

CREATE TABLE EATS_MENU AS SELECT * FROM MENU;

SELECT * FROM EATS_MENU;

-- 11번째 빠나쁘레쏘 '경기도 고양시' '031-123-4567'

INSERT INTO EATS VALUES (11, '빠나쁘레쏘', '경기도 고양시', '031-123-4567');

COMMIT;

INSERT INTO EATS VALUES (12, '로맨틱블루', '부산 해운대구', '051-987-6543');

INSERT INTO EATS VALUES (13, '티하우스', '인천 남동구', '032-345-6789');
INSERT INTO EATS VALUES (14, '라떼아트', '경기도 성남시', '031-654-3210');
INSERT INTO EATS(CAFE_NAME, LOCATION, CONTACT_NUMBER) VALUES('커피클럽', '대구 중구', '053-222-1111');
SELECT * FROM EATS;
COMMIT;

ROLLBACK; --DBeaver는 자동 COMMIT 한다

DELETE FROM EATS WHERE location = '대구 중구';
-- NOT NULL은 필수 작성	

INSERT INTO EATS(CAFE_ID, CAFE_NAME) VALUES (15, '빈포레스트'); 
-- PRIMARY KEY : UNIQUE (NULL 가능) // ORACLE만 INCREMENT 적용 x

-- 트리거 시퀀스 -> ORACLE PRIMARY KEY는 자동으로 번호를 측정해주는 동작을 설정해줘야함
DELETE FROM EATS WHERE CAFE_NAME ='빈포레스트';

INSERT INTO EATS(CAFE_ID, CAFE_NAME, LOCATION, CONTACT_NUMBER) VALUES (16, '블루윙랩', '대전 서구', '042-333-4444');
INSERT INTO EATS(CAFE_ID, CAFE_NAME, LOCATION, CONTACT_NUMBER) VALUES (17, '스윙빈즈', '광주 북구', '062-567-8901');
INSERT INTO EATS(CAFE_ID, CAFE_NAME, LOCATION, CONTACT_NUMBER) VALUES (18, '카페 블랙', '울산 남구', '052-444-5555');
UPDATE EATS SET CAFE_NAME = '브루윙랩' WHERE CAFE_ID = 16;
UPDATE EATS SET CAFE_NAME = '스윗빈즈' WHERE CAFE_ID = 17;